export const backgroundThemes = {
  midnight: {
    name: 'Midnight',
    bgPrimary: '#111827',
    bgSecondary: '#1f2937',
    bgTertiary: '#374151',
    textPrimary: '#ffffff',
    textSecondary: '#9ca3af',
    borderColor: '#374151',
    isLight: false,
  },
  slate: {
    name: 'Slate',
    bgPrimary: '#0f172a',
    bgSecondary: '#1e293b',
    bgTertiary: '#334155',
    textPrimary: '#ffffff',
    textSecondary: '#94a3b8',
    borderColor: '#334155',
    isLight: false,
  },
  ocean: {
    name: 'Ocean',
    bgPrimary: '#0c1929',
    bgSecondary: '#152238',
    bgTertiary: '#1e3a5f',
    textPrimary: '#ffffff',
    textSecondary: '#7dd3fc',
    borderColor: '#1e3a5f',
    isLight: false,
  },
  paper: {
    name: 'Paper',
    bgPrimary: '#faf7f2',
    bgSecondary: '#f0ebe3',
    bgTertiary: '#e6e0d4',
    textPrimary: '#1f2937',
    textSecondary: '#6b7280',
    borderColor: '#d1d5db',
    isLight: true,
  },
  snow: {
    name: 'Snow',
    bgPrimary: '#ffffff',
    bgSecondary: '#f8fafc',
    bgTertiary: '#f1f5f9',
    textPrimary: '#111827',
    textSecondary: '#6b7280',
    borderColor: '#e5e7eb',
    isLight: true,
  },
} as const

export type BackgroundTheme = keyof typeof backgroundThemes